version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "readme-post"
      POSTGRES_PASSWORD: "test"
    healthcheck:
      test: ["CMD", "pg_isready -U admin -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "chinatruckspb@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge