
//Регистрация нового пользователя
POST  http://localhost:3333/api/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "chinatruckspb@gmail.com",
  "firstname": "Evgeniy",
  "lastname": "Kharitonov",
  "password": "123456",
  "dateRegister": "2022-01-20"
}

###

//Авторизация польвателя
GET http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "chinatruckspb@gmail.com",
  "password": "123456"
}

###